{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.2.1.aar",
          "url": "AndroidBase-1.2.1.aar",
          "size": 101144,
          "sha512": "0746a9e3a5a5f29a2ae2a19e76eaa8111163803670fd0c3867c691581d4c8046495923d861ef1b1e544ed5a668f08834804a9ebe2a258bd06d8564cdf994597f",
          "sha256": "434c86a1aee257b6a402ee8f6dc52c3c295f2f7820fc1a80b09046338b0213a1",
          "sha1": "3aac57d5e122b07db774ed61fc0c9ec586a92ad9",
          "md5": "f1a7a0b32cc935ce709f74e639dd284c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.2.1.aar",
          "url": "AndroidBase-1.2.1.aar",
          "size": 101144,
          "sha512": "0746a9e3a5a5f29a2ae2a19e76eaa8111163803670fd0c3867c691581d4c8046495923d861ef1b1e544ed5a668f08834804a9ebe2a258bd06d8564cdf994597f",
          "sha256": "434c86a1aee257b6a402ee8f6dc52c3c295f2f7820fc1a80b09046338b0213a1",
          "sha1": "3aac57d5e122b07db774ed61fc0c9ec586a92ad9",
          "md5": "f1a7a0b32cc935ce709f74e639dd284c"
        }
      ]
    }
  ]
}
