{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.3.aar",
          "url": "AndroidBase-1.0.3.aar",
          "size": 81208,
          "sha512": "3918dbf003417c08ac552c20d365cbc2f94dd98ad08244328bdbf659f94c5d89ce7b4dff76590627f393e43242818e14e3fb36beed1c3a9906626bfc74eb9ae6",
          "sha256": "909711df371c65ca972e0ca657ccc581e1d9742dee9ae2e28b2c6d9406145675",
          "sha1": "ad7d33378244f1dc790c5e7d325579fee12f4853",
          "md5": "b80a486de75363ad4b4b6740bb291239"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.3.aar",
          "url": "AndroidBase-1.0.3.aar",
          "size": 81208,
          "sha512": "3918dbf003417c08ac552c20d365cbc2f94dd98ad08244328bdbf659f94c5d89ce7b4dff76590627f393e43242818e14e3fb36beed1c3a9906626bfc74eb9ae6",
          "sha256": "909711df371c65ca972e0ca657ccc581e1d9742dee9ae2e28b2c6d9406145675",
          "sha1": "ad7d33378244f1dc790c5e7d325579fee12f4853",
          "md5": "b80a486de75363ad4b4b6740bb291239"
        }
      ]
    }
  ]
}
