{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.1.1.aar",
          "url": "Shade-1.1.1.aar",
          "size": 60326,
          "sha512": "ca51d81759fa790c68d2ef6c6280f8b798ad9836508bbb2f54e3d1f77dd082023d808ea49a2f33b4355b4804296b23ae67bb3e1e95cc75f41f2e037dfba2ddb0",
          "sha256": "fc6ec3b1af70cf03f08e6e94fb90244124461b24d847488c965626a9ba0d0060",
          "sha1": "ef90da2c231fd6b60ec30f7feb56c8c8a55fd624",
          "md5": "74396b3814aef6ffdc37da0dceedc2b8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.1.1.aar",
          "url": "Shade-1.1.1.aar",
          "size": 60326,
          "sha512": "ca51d81759fa790c68d2ef6c6280f8b798ad9836508bbb2f54e3d1f77dd082023d808ea49a2f33b4355b4804296b23ae67bb3e1e95cc75f41f2e037dfba2ddb0",
          "sha256": "fc6ec3b1af70cf03f08e6e94fb90244124461b24d847488c965626a9ba0d0060",
          "sha1": "ef90da2c231fd6b60ec30f7feb56c8c8a55fd624",
          "md5": "74396b3814aef6ffdc37da0dceedc2b8"
        }
      ]
    }
  ]
}
