{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.6.4.aar",
          "url": "AndroidBase-1.6.4.aar",
          "size": 169785,
          "sha512": "e469bfa4a02e2be3efa7b424f467990c8e56a5d61ef50a1ecb6149c93a9e3d35b8a685c49f85c15581e8febdba1d833d7c1b138d96ae16d9fd93cfdad8efe1c6",
          "sha256": "76e652a2256a6a21c37dedaf1b6ab59b497d1c1d573c2f27dd7e265ec1263b93",
          "sha1": "3fb5982b00d5630725fea63f23208b4ee97baada",
          "md5": "caa255bfe3c4b9c4f10dc0a7399ac9ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.6.4.aar",
          "url": "AndroidBase-1.6.4.aar",
          "size": 169785,
          "sha512": "e469bfa4a02e2be3efa7b424f467990c8e56a5d61ef50a1ecb6149c93a9e3d35b8a685c49f85c15581e8febdba1d833d7c1b138d96ae16d9fd93cfdad8efe1c6",
          "sha256": "76e652a2256a6a21c37dedaf1b6ab59b497d1c1d573c2f27dd7e265ec1263b93",
          "sha1": "3fb5982b00d5630725fea63f23208b4ee97baada",
          "md5": "caa255bfe3c4b9c4f10dc0a7399ac9ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AndroidBase-1.6.4-sources.jar",
          "url": "AndroidBase-1.6.4-sources.jar",
          "size": 37946,
          "sha512": "5e2bcba22bc2f779a6012c12911f7502bfa01d0442ae6dccca3111edf4490592ef9179925121dab82a2aecd9e1570b7aecdf586e91d16713f9231e122ec01c71",
          "sha256": "bd3ffde5e9ddfa3dc9499482e49d2ae7ad796b0deb4f532bfecab126a4b488e8",
          "sha1": "68e0da31173db0b744d43c5df9ec86cf77c3947d",
          "md5": "8f81d05ee6bfd1c1add5430cb39b8a96"
        }
      ]
    }
  ]
}
