{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.3.aar",
          "url": "Shade-1.3.3.aar",
          "size": 85309,
          "sha512": "fa6a6b5e6771468906515832aa3cba33a292c7b38190cb446cda38c22e2f0929d33ca9776a0a541b6a1f2fc4019500bc2057ea41ae759eb37bce64379bb9f044",
          "sha256": "3cff70a88976a61e7863db83bbc06381c0d1d86976c2f09db20695313f68ae7b",
          "sha1": "fe5337d0a36805cf1acbf83bb221973c7886996f",
          "md5": "edbb9f8ac77be14ce7a970291ca19dac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.3.aar",
          "url": "Shade-1.3.3.aar",
          "size": 85309,
          "sha512": "fa6a6b5e6771468906515832aa3cba33a292c7b38190cb446cda38c22e2f0929d33ca9776a0a541b6a1f2fc4019500bc2057ea41ae759eb37bce64379bb9f044",
          "sha256": "3cff70a88976a61e7863db83bbc06381c0d1d86976c2f09db20695313f68ae7b",
          "sha1": "fe5337d0a36805cf1acbf83bb221973c7886996f",
          "md5": "edbb9f8ac77be14ce7a970291ca19dac"
        }
      ]
    }
  ]
}
