{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.1.aar",
          "url": "Shade-1.2.1.aar",
          "size": 61811,
          "sha512": "f68bbb1c5d2a149bb1c9ebf06c64484253cf3fec4a81fe9ffcfe60aa5c8519d53aceaeedce340d018875890da63d7429ecce0fdddb9d6fe0b7f5592c38641288",
          "sha256": "a0e7f0f6c2db06a38ad972149ba79694be46272ed3a59a22e009017bbfa39c84",
          "sha1": "33dd9ac68c8aaa70237475c214e099e8f002291b",
          "md5": "d95fa9f5fe415448d3e0912eee151da5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.1.aar",
          "url": "Shade-1.2.1.aar",
          "size": 61811,
          "sha512": "f68bbb1c5d2a149bb1c9ebf06c64484253cf3fec4a81fe9ffcfe60aa5c8519d53aceaeedce340d018875890da63d7429ecce0fdddb9d6fe0b7f5592c38641288",
          "sha256": "a0e7f0f6c2db06a38ad972149ba79694be46272ed3a59a22e009017bbfa39c84",
          "sha1": "33dd9ac68c8aaa70237475c214e099e8f002291b",
          "md5": "d95fa9f5fe415448d3e0912eee151da5"
        }
      ]
    }
  ]
}
