{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.4.3.aar",
          "url": "Shade-1.4.3.aar",
          "size": 104473,
          "sha512": "5b1739f2aedb49725070b18c01c75aaad3d4d4a253b81f890bf551a62f5e230db61dc4a71b2c24587fd7f1dc4024b50d23fc4acae8ca29b6443805122341ef5f",
          "sha256": "ccf8beadc3f73e91640d88485646d8f1217302913fdebd3e8c78bb3ea21ae1de",
          "sha1": "3d02b7485d8cbe6a744db415a3ee43a6046bb834",
          "md5": "6bbfb3b60edcb587d33a50647bafa3a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.4.3.aar",
          "url": "Shade-1.4.3.aar",
          "size": 104473,
          "sha512": "5b1739f2aedb49725070b18c01c75aaad3d4d4a253b81f890bf551a62f5e230db61dc4a71b2c24587fd7f1dc4024b50d23fc4acae8ca29b6443805122341ef5f",
          "sha256": "ccf8beadc3f73e91640d88485646d8f1217302913fdebd3e8c78bb3ea21ae1de",
          "sha1": "3d02b7485d8cbe6a744db415a3ee43a6046bb834",
          "md5": "6bbfb3b60edcb587d33a50647bafa3a0"
        }
      ]
    }
  ]
}
