{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.2.aar",
          "url": "AndroidBase-1.0.2.aar",
          "size": 77624,
          "sha512": "fee303b952dc32f7f8b3e8d58a58c53bb29b0fd7aae4e382039ccaf01c1c4bbfe9c6e75d375504efb99dcf1366bc8d7bef2417edc264c49c73e96fc0f9441d4b",
          "sha256": "4c628c28beeaae72b91eaad65057db4957f2629628ea9e905600335b0e3a2572",
          "sha1": "137fc7c13fddac4274356a00c017f7de02fa6659",
          "md5": "15dbbdf89efa34581e252fb821e24b6e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.2.aar",
          "url": "AndroidBase-1.0.2.aar",
          "size": 77624,
          "sha512": "fee303b952dc32f7f8b3e8d58a58c53bb29b0fd7aae4e382039ccaf01c1c4bbfe9c6e75d375504efb99dcf1366bc8d7bef2417edc264c49c73e96fc0f9441d4b",
          "sha256": "4c628c28beeaae72b91eaad65057db4957f2629628ea9e905600335b0e3a2572",
          "sha1": "137fc7c13fddac4274356a00c017f7de02fa6659",
          "md5": "15dbbdf89efa34581e252fb821e24b6e"
        }
      ]
    }
  ]
}
