{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.6.5.aar",
          "url": "AndroidBase-1.6.5.aar",
          "size": 172933,
          "sha512": "e57ccd36d32f8510c9b8d23db69e8fb0f613ba998b45290a1097375db54a1b2623dabe987f62f723acc31089e015d170d8a8268d70922226585d12339c4cc671",
          "sha256": "b5cd3db0b15d470cec993edc6d7d1e2cf2a89a6eb83251c384e203e09d604a6b",
          "sha1": "aa621593a675ef43f14155b73b69dd3b0595df9b",
          "md5": "0edf30165a0a82fb2d51b900ba0fbd84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.6.5.aar",
          "url": "AndroidBase-1.6.5.aar",
          "size": 172933,
          "sha512": "e57ccd36d32f8510c9b8d23db69e8fb0f613ba998b45290a1097375db54a1b2623dabe987f62f723acc31089e015d170d8a8268d70922226585d12339c4cc671",
          "sha256": "b5cd3db0b15d470cec993edc6d7d1e2cf2a89a6eb83251c384e203e09d604a6b",
          "sha1": "aa621593a675ef43f14155b73b69dd3b0595df9b",
          "md5": "0edf30165a0a82fb2d51b900ba0fbd84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AndroidBase-1.6.5-sources.jar",
          "url": "AndroidBase-1.6.5-sources.jar",
          "size": 37291,
          "sha512": "af58727ae89890ed30477664706093695a14fe580431243b595871161c96aa2b0c71ec15da218066bd52b4f3d5234f64b6a07b472f5a84066a07fd293686de72",
          "sha256": "70fcf915fcc2993af69d9e061ad4055b9252178e0d245bacb06ddbb05ba367f1",
          "sha1": "dd0cc663a2924657ec6ef4cc7a122abea51b37e9",
          "md5": "a01f236539c8e0055d2d7f4c2aac48ff"
        }
      ]
    }
  ]
}
