{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "AndroidBase",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.4.3.aar",
          "url": "AndroidBase-1.4.3.aar",
          "size": 143975,
          "sha512": "7f77e316e51efb84fc555f4c98e6c73488c0c94b1ddb1d722370efb6aaed4a0311d97b9d5bf07fa27dc7f65865d61eb7747589544c0f291cacd848e19c5d7926",
          "sha256": "b58f3d2ee1198d2d19653d271a80a19caa147eca5b7086abfb343f0230553408",
          "sha1": "49b33017cb4064a778183ff5bc01c571b02705b9",
          "md5": "45ac0d53630577eff7d03677e9fffc28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.4.3.aar",
          "url": "AndroidBase-1.4.3.aar",
          "size": 143975,
          "sha512": "7f77e316e51efb84fc555f4c98e6c73488c0c94b1ddb1d722370efb6aaed4a0311d97b9d5bf07fa27dc7f65865d61eb7747589544c0f291cacd848e19c5d7926",
          "sha256": "b58f3d2ee1198d2d19653d271a80a19caa147eca5b7086abfb343f0230553408",
          "sha1": "49b33017cb4064a778183ff5bc01c571b02705b9",
          "md5": "45ac0d53630577eff7d03677e9fffc28"
        }
      ]
    }
  ]
}
