{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.0.3.aar",
          "url": "Shade-1.0.3.aar",
          "size": 57577,
          "sha512": "34d8ecee85af174dd8c21e8870734060ecabdfabc7432eb4866a36149d9da6db896b1297303e4cf65ecab32ca6f93b503b72101c05217730fd86c2b0cc67c4e9",
          "sha256": "fd6d68feea8190fc48627411f83f11bd916b0dabf05a4ac9085c7c850622fea1",
          "sha1": "fc03e1b8a0b95b1c9c888061400b04fdc5e22c96",
          "md5": "b466d346da386816beb25930cdc5cb74"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.0.3.aar",
          "url": "Shade-1.0.3.aar",
          "size": 57577,
          "sha512": "34d8ecee85af174dd8c21e8870734060ecabdfabc7432eb4866a36149d9da6db896b1297303e4cf65ecab32ca6f93b503b72101c05217730fd86c2b0cc67c4e9",
          "sha256": "fd6d68feea8190fc48627411f83f11bd916b0dabf05a4ac9085c7c850622fea1",
          "sha1": "fc03e1b8a0b95b1c9c888061400b04fdc5e22c96",
          "md5": "b466d346da386816beb25930cdc5cb74"
        }
      ]
    }
  ]
}
