{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidWidget",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.0.0.aar",
          "url": "AndroidWidget-1.0.0.aar",
          "size": 48894,
          "sha512": "479db04bfd561ced3e779c0c710e09fad8fba50aa4a4f9112605dbedee3088897d618744f943107ce94d850125be6b817326ff02b753afa7eeb97eecf6e7a3c0",
          "sha256": "7ed39871e74bf5b781a735087498c59127c434286fbe2ca7252c7d57127e5711",
          "sha1": "3736d5be95a4010007ce89bd152947ff53e5178a",
          "md5": "ce716cef2314612b59bde3cfe5e8ab95"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.0.0.aar",
          "url": "AndroidWidget-1.0.0.aar",
          "size": 48894,
          "sha512": "479db04bfd561ced3e779c0c710e09fad8fba50aa4a4f9112605dbedee3088897d618744f943107ce94d850125be6b817326ff02b753afa7eeb97eecf6e7a3c0",
          "sha256": "7ed39871e74bf5b781a735087498c59127c434286fbe2ca7252c7d57127e5711",
          "sha1": "3736d5be95a4010007ce89bd152947ff53e5178a",
          "md5": "ce716cef2314612b59bde3cfe5e8ab95"
        }
      ]
    }
  ]
}
