{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidWidget",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.4.0.aar",
          "url": "AndroidWidget-1.4.0.aar",
          "size": 94951,
          "sha512": "7395ab28ec7ee1b020e70e42c8bbc8302b13ed91d7ea284f0eea6dcd1993e202498e8fcf76a6247a7f3316637764d5d132a9d6f88029d47d2c0f013ed800e318",
          "sha256": "ab65b8265b168992971fc5eb7821d4b611f2f1368cd033b32e8971140e44069d",
          "sha1": "4a3aca7401cad691b29365a061c0b78dbd6ff40b",
          "md5": "1fba05d48cd70133e0691c6ad44b58dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.4.0.aar",
          "url": "AndroidWidget-1.4.0.aar",
          "size": 94951,
          "sha512": "7395ab28ec7ee1b020e70e42c8bbc8302b13ed91d7ea284f0eea6dcd1993e202498e8fcf76a6247a7f3316637764d5d132a9d6f88029d47d2c0f013ed800e318",
          "sha256": "ab65b8265b168992971fc5eb7821d4b611f2f1368cd033b32e8971140e44069d",
          "sha1": "4a3aca7401cad691b29365a061c0b78dbd6ff40b",
          "md5": "1fba05d48cd70133e0691c6ad44b58dd"
        }
      ]
    }
  ]
}
