{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidWidget",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.3.2.aar",
          "url": "AndroidWidget-1.3.2.aar",
          "size": 89049,
          "sha512": "0930e9b54ba294e720393e1cafde7ede0fb44b6b7eead03ccf8255f04112c14b6b88f50cb87fa859eae8e513ad35b53319016d8e2ca8f3477c89de9b62dbf41e",
          "sha256": "aa564b286edea93e702c0e872a8c018fe6394cea4b8bb6f7986ea7661f97ca8c",
          "sha1": "d026e2400cc21c4958c0775c7b1cb620ab824603",
          "md5": "deb3ddc28555e4050925e3245b40d64b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.3.2.aar",
          "url": "AndroidWidget-1.3.2.aar",
          "size": 89049,
          "sha512": "0930e9b54ba294e720393e1cafde7ede0fb44b6b7eead03ccf8255f04112c14b6b88f50cb87fa859eae8e513ad35b53319016d8e2ca8f3477c89de9b62dbf41e",
          "sha256": "aa564b286edea93e702c0e872a8c018fe6394cea4b8bb6f7986ea7661f97ca8c",
          "sha1": "d026e2400cc21c4958c0775c7b1cb620ab824603",
          "md5": "deb3ddc28555e4050925e3245b40d64b"
        }
      ]
    }
  ]
}
