{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "AndroidWidget",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.4.1.aar",
          "url": "AndroidWidget-1.4.1.aar",
          "size": 103899,
          "sha512": "f15efdc2c96793c54cb35d822851c016cfefed718b3cf80e21415051ad26291706d12c7a8d230228fbdad9217198da0066b886f74e270db067847aa2253ee447",
          "sha256": "d731fdcfd3158f831a7f19365d412964fef01b166a182aab142eac986f9fa654",
          "sha1": "1f25eff302c5f01eda794f88585cf39ae711258d",
          "md5": "632936b9f3824adcaec4f1a6e7faab6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.4.1.aar",
          "url": "AndroidWidget-1.4.1.aar",
          "size": 103899,
          "sha512": "f15efdc2c96793c54cb35d822851c016cfefed718b3cf80e21415051ad26291706d12c7a8d230228fbdad9217198da0066b886f74e270db067847aa2253ee447",
          "sha256": "d731fdcfd3158f831a7f19365d412964fef01b166a182aab142eac986f9fa654",
          "sha1": "1f25eff302c5f01eda794f88585cf39ae711258d",
          "md5": "632936b9f3824adcaec4f1a6e7faab6b"
        }
      ]
    }
  ]
}
