{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "AndroidWidget",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.3.0.aar",
          "url": "AndroidWidget-1.3.0.aar",
          "size": 84390,
          "sha512": "844567370c696808bc543791eb16d54463ac18b14192591a8414bfc038ce80119bb4b2fb232f873244e2a6c33b5a8562cc344c22b13da8cbf2775fe93054d4bc",
          "sha256": "a28e7a81330cc9971a1c5ce6da8ee60089ef146845ebca4e26e99f996c9e2556",
          "sha1": "0a7742aa14eb351b74fe95d71f66255f655ca7f6",
          "md5": "1e758017bc3a9e622183c576b9eec526"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.3.0.aar",
          "url": "AndroidWidget-1.3.0.aar",
          "size": 84390,
          "sha512": "844567370c696808bc543791eb16d54463ac18b14192591a8414bfc038ce80119bb4b2fb232f873244e2a6c33b5a8562cc344c22b13da8cbf2775fe93054d4bc",
          "sha256": "a28e7a81330cc9971a1c5ce6da8ee60089ef146845ebca4e26e99f996c9e2556",
          "sha1": "0a7742aa14eb351b74fe95d71f66255f655ca7f6",
          "md5": "1e758017bc3a9e622183c576b9eec526"
        }
      ]
    }
  ]
}
