{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "AndroidBase",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.1.1.aar",
          "url": "AndroidBase-1.1.1.aar",
          "size": 95849,
          "sha512": "595af169034344ddc3ea820bfa9acd1d7270564e324818c0d7f91a7afe4f716b7fad897d3d997bcf8a1fe31ca0446e183d53b07c23cd7fa181fbeaaa3beddb44",
          "sha256": "79265f4aaf316f3d49e9d83a7dfcae29f7d53e11e46847b621c75b0528cd8b1f",
          "sha1": "b410e9974c76b5cfa175d0a9c19cedf5482c81f7",
          "md5": "bdb1092d1e7a9ed8163ee653b25597c9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.1.1.aar",
          "url": "AndroidBase-1.1.1.aar",
          "size": 95849,
          "sha512": "595af169034344ddc3ea820bfa9acd1d7270564e324818c0d7f91a7afe4f716b7fad897d3d997bcf8a1fe31ca0446e183d53b07c23cd7fa181fbeaaa3beddb44",
          "sha256": "79265f4aaf316f3d49e9d83a7dfcae29f7d53e11e46847b621c75b0528cd8b1f",
          "sha1": "b410e9974c76b5cfa175d0a9c19cedf5482c81f7",
          "md5": "bdb1092d1e7a9ed8163ee653b25597c9"
        }
      ]
    }
  ]
}
