{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.0.aar",
          "url": "Shade-1.3.0.aar",
          "size": 68774,
          "sha512": "cf629fb26ee31cf878b9b58889ea46c96fbb881741176d6a29158656c49a199bb09ad18cade870cc1604ad0293650d98c23a442b4c107a970f8e18b1b7616dc2",
          "sha256": "b8538dd239aca591216f368a265fc723fe3de6b5d79acdaf7e5a19673bb14e42",
          "sha1": "bcda6512e8f14c004b13546cf0e3a112e0919bec",
          "md5": "5b3a9906113b5704cafd7c62ee8c0d97"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.0.aar",
          "url": "Shade-1.3.0.aar",
          "size": 68774,
          "sha512": "cf629fb26ee31cf878b9b58889ea46c96fbb881741176d6a29158656c49a199bb09ad18cade870cc1604ad0293650d98c23a442b4c107a970f8e18b1b7616dc2",
          "sha256": "b8538dd239aca591216f368a265fc723fe3de6b5d79acdaf7e5a19673bb14e42",
          "sha1": "bcda6512e8f14c004b13546cf0e3a112e0919bec",
          "md5": "5b3a9906113b5704cafd7c62ee8c0d97"
        }
      ]
    }
  ]
}
