{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.0.aar",
          "url": "AndroidBase-1.0.0.aar",
          "size": 56007,
          "sha512": "37f4469009c3b53a5b26beaa659cc391e8068229b4c04f9278310e62cac4d5af50158b77ac8f527c6efb01313df91c4203319dc4f86c3ea6568bdee6793d5bb8",
          "sha256": "c10db67ae497dc2d5368dbcc59b33a96d550744014c381057b822c0b0411a640",
          "sha1": "6bd039d409d3a6b42e0d9357bb5c9576580937d9",
          "md5": "7ff643f4451f065413125817173d3af5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.0.aar",
          "url": "AndroidBase-1.0.0.aar",
          "size": 56007,
          "sha512": "37f4469009c3b53a5b26beaa659cc391e8068229b4c04f9278310e62cac4d5af50158b77ac8f527c6efb01313df91c4203319dc4f86c3ea6568bdee6793d5bb8",
          "sha256": "c10db67ae497dc2d5368dbcc59b33a96d550744014c381057b822c0b0411a640",
          "sha1": "6bd039d409d3a6b42e0d9357bb5c9576580937d9",
          "md5": "7ff643f4451f065413125817173d3af5"
        }
      ]
    }
  ]
}
