{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.1.0.aar",
          "url": "Shade-1.1.0.aar",
          "size": 59918,
          "sha512": "beeea2e76358b2cc63185149beb0b40032f1e027b911bf36ae302afd7c309f3d1095c4320b9b40691c428ec4178d6ff8eafdf1a504c16b4561a42ab223e2cea6",
          "sha256": "ba3e6ee2314c60cddffd451f91730dc19ef57c65d31146c0d86552ad837cf872",
          "sha1": "3337adc4b08bb97882c2177423fa080d563d1440",
          "md5": "7e55d688ad8242290ca4508b8e45ab9d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.1.0.aar",
          "url": "Shade-1.1.0.aar",
          "size": 59918,
          "sha512": "beeea2e76358b2cc63185149beb0b40032f1e027b911bf36ae302afd7c309f3d1095c4320b9b40691c428ec4178d6ff8eafdf1a504c16b4561a42ab223e2cea6",
          "sha256": "ba3e6ee2314c60cddffd451f91730dc19ef57c65d31146c0d86552ad837cf872",
          "sha1": "3337adc4b08bb97882c2177423fa080d563d1440",
          "md5": "7e55d688ad8242290ca4508b8e45ab9d"
        }
      ]
    }
  ]
}
