{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidWidget",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.7.0.aar",
          "url": "AndroidWidget-1.7.0.aar",
          "size": 189538,
          "sha512": "519f57e67b13b6cce01955cc0d838beed8664c37db4d812b0d95d0337971f370c195dfb9ea0833e9e326884f2256bdb7dcb7e37a1f846abd06c042f4a9a4c52d",
          "sha256": "1e69a148d2435b6309ae6bbe0a03b42852a8cf2dad7d2a32c818e1eec7fd2037",
          "sha1": "7638117d5b8bef30b4279cb5b80fd5892fb5fb49",
          "md5": "e4c3e76f443f348c4de168c6abaa7204"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.7.0.aar",
          "url": "AndroidWidget-1.7.0.aar",
          "size": 189538,
          "sha512": "519f57e67b13b6cce01955cc0d838beed8664c37db4d812b0d95d0337971f370c195dfb9ea0833e9e326884f2256bdb7dcb7e37a1f846abd06c042f4a9a4c52d",
          "sha256": "1e69a148d2435b6309ae6bbe0a03b42852a8cf2dad7d2a32c818e1eec7fd2037",
          "sha1": "7638117d5b8bef30b4279cb5b80fd5892fb5fb49",
          "md5": "e4c3e76f443f348c4de168c6abaa7204"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AndroidWidget-1.7.0-sources.jar",
          "url": "AndroidWidget-1.7.0-sources.jar",
          "size": 41982,
          "sha512": "12342da5a7e84d6ac90010ad94c42c09840c8528bdf494f311f476dcfa69442fb47a734bc576376cb6d89a93d5684b3eceab5b4bd95c55f134e8da323ce9b004",
          "sha256": "c830ca90ebdf39801cebc33325aae1e4e40adfbbc8a9b696c4fbd4830efb7db9",
          "sha1": "f2256083522446efbf2f367a55414e279e3acb7a",
          "md5": "74a924a733d8f7cc9c4f5558af6d09a9"
        }
      ]
    }
  ]
}
