{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.5.6.aar",
          "url": "AndroidBase-1.5.6.aar",
          "size": 168524,
          "sha512": "2333dfb92487549407c7425ded47fae6549a82b0d3c6e82d31449d3116c5a379d946d9b5c17755888cfbae7aa93c4b0dde931aea0b14a336ac02cde7c7c418f6",
          "sha256": "c2ac0d81b08811b295a0c3476a24c38bbe076eff1a7228dd5da91170c6c93244",
          "sha1": "bb426a11e1873bffafa64c8e1cb6882e93371caf",
          "md5": "fcaa330c7885fe51bb6d6e2ba0ee76cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.5.6.aar",
          "url": "AndroidBase-1.5.6.aar",
          "size": 168524,
          "sha512": "2333dfb92487549407c7425ded47fae6549a82b0d3c6e82d31449d3116c5a379d946d9b5c17755888cfbae7aa93c4b0dde931aea0b14a336ac02cde7c7c418f6",
          "sha256": "c2ac0d81b08811b295a0c3476a24c38bbe076eff1a7228dd5da91170c6c93244",
          "sha1": "bb426a11e1873bffafa64c8e1cb6882e93371caf",
          "md5": "fcaa330c7885fe51bb6d6e2ba0ee76cb"
        }
      ]
    }
  ]
}
