{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.5.aar",
          "url": "Shade-1.3.5.aar",
          "size": 88444,
          "sha512": "ebe9cbeb6089c76198c32b51b3bccefb0ea3829e7c954b0e01033b0951c43cf1fe1f21e489d342a943ce201de296de8a8c41a8a1ed3afe3ece89554950652c02",
          "sha256": "fa7afa2d9b83f4d90d361c4468f437ba986cead99b3252767b2421506d6224d2",
          "sha1": "e256a73ebebb3867b1c8cec7097c1dcd43a0bb0d",
          "md5": "3ebe59c3a8f7cbf32cd182c45c97f05c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.5.aar",
          "url": "Shade-1.3.5.aar",
          "size": 88444,
          "sha512": "ebe9cbeb6089c76198c32b51b3bccefb0ea3829e7c954b0e01033b0951c43cf1fe1f21e489d342a943ce201de296de8a8c41a8a1ed3afe3ece89554950652c02",
          "sha256": "fa7afa2d9b83f4d90d361c4468f437ba986cead99b3252767b2421506d6224d2",
          "sha1": "e256a73ebebb3867b1c8cec7097c1dcd43a0bb0d",
          "md5": "3ebe59c3a8f7cbf32cd182c45c97f05c"
        }
      ]
    }
  ]
}
