{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.5.1.aar",
          "url": "AndroidBase-1.5.1.aar",
          "size": 146985,
          "sha512": "1a3a2768f5b6d7fd691c07a1d1c22fd4818a0760911d89df5d50046ee7966afa90efef5e31660076b150e627a975f316390494eb58f6925ebe2cd6fec7e7bbe3",
          "sha256": "f0ba89643068aa4993f170c57a6eacbd8584d2ac4ab5cf94681eb87615eb6351",
          "sha1": "19360f31709cd19e90bcd234c74e5effd12a29f2",
          "md5": "a4c18475b3652505a7ed8385e7433fc6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.5.1.aar",
          "url": "AndroidBase-1.5.1.aar",
          "size": 146985,
          "sha512": "1a3a2768f5b6d7fd691c07a1d1c22fd4818a0760911d89df5d50046ee7966afa90efef5e31660076b150e627a975f316390494eb58f6925ebe2cd6fec7e7bbe3",
          "sha256": "f0ba89643068aa4993f170c57a6eacbd8584d2ac4ab5cf94681eb87615eb6351",
          "sha1": "19360f31709cd19e90bcd234c74e5effd12a29f2",
          "md5": "a4c18475b3652505a7ed8385e7433fc6"
        }
      ]
    }
  ]
}
