{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "AndroidWidget",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.4.6.aar",
          "url": "AndroidWidget-1.4.6.aar",
          "size": 124662,
          "sha512": "6ff52038d58d4df203c51df59f321d1d92fb612104fc6d08e509356636816ec0a7832b3e4b3b1bdd0fb73f5705ce6a74d048c710ee2a2d908a79130e2faec5ac",
          "sha256": "3e52a2be3f4a3fee1afc6a7bad7abe5528f9226117cfb38e43044e096aaf6b41",
          "sha1": "048b87bf0326b73d9d2c235cda32cda1d4767069",
          "md5": "5fece34a4a090cd1003326838c7408ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "DimensionUtil",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.4.6.aar",
          "url": "AndroidWidget-1.4.6.aar",
          "size": 124662,
          "sha512": "6ff52038d58d4df203c51df59f321d1d92fb612104fc6d08e509356636816ec0a7832b3e4b3b1bdd0fb73f5705ce6a74d048c710ee2a2d908a79130e2faec5ac",
          "sha256": "3e52a2be3f4a3fee1afc6a7bad7abe5528f9226117cfb38e43044e096aaf6b41",
          "sha1": "048b87bf0326b73d9d2c235cda32cda1d4767069",
          "md5": "5fece34a4a090cd1003326838c7408ae"
        }
      ]
    }
  ]
}
