{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.3.5.aar",
          "url": "AndroidBase-1.3.5.aar",
          "size": 118947,
          "sha512": "40e1d6f8aaa57ab817d41bb392b4e159e65549e4ad5b6a87686c90f44c6fe49724b30fa21206a7ae247c6a68b85a9abf929ef77e50255e7c42300677711f8987",
          "sha256": "a73c5eefa0e7adeade58f6566ab4cf7684776532410f2aa9cd15b3ab39216395",
          "sha1": "7937c8921d5336ca434cdd01574ebdce16089e10",
          "md5": "48dfa9f45fade3470edc30c24fb80ad3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.3.5.aar",
          "url": "AndroidBase-1.3.5.aar",
          "size": 118947,
          "sha512": "40e1d6f8aaa57ab817d41bb392b4e159e65549e4ad5b6a87686c90f44c6fe49724b30fa21206a7ae247c6a68b85a9abf929ef77e50255e7c42300677711f8987",
          "sha256": "a73c5eefa0e7adeade58f6566ab4cf7684776532410f2aa9cd15b3ab39216395",
          "sha1": "7937c8921d5336ca434cdd01574ebdce16089e10",
          "md5": "48dfa9f45fade3470edc30c24fb80ad3"
        }
      ]
    }
  ]
}
