{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.4.1.aar",
          "url": "Shade-1.4.1.aar",
          "size": 99057,
          "sha512": "0e1afbaed6de59480518375ab5bf84c3aa3d6a9a4d2549acdfec8d1db6a4540031c2ff3001cf821cbc703516be4ced1091175fe191a5a98ad3bf148ec53e366d",
          "sha256": "ade7762fc8515d64a23cf0c304c7bea0873b76f3bc1c2ed22d639686ab9813a4",
          "sha1": "d862029a5ba0899eebf4fc7011001bd303d3073d",
          "md5": "b9d4df7d2fe67da437069c72b17bbb5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.4.1.aar",
          "url": "Shade-1.4.1.aar",
          "size": 99057,
          "sha512": "0e1afbaed6de59480518375ab5bf84c3aa3d6a9a4d2549acdfec8d1db6a4540031c2ff3001cf821cbc703516be4ced1091175fe191a5a98ad3bf148ec53e366d",
          "sha256": "ade7762fc8515d64a23cf0c304c7bea0873b76f3bc1c2ed22d639686ab9813a4",
          "sha1": "d862029a5ba0899eebf4fc7011001bd303d3073d",
          "md5": "b9d4df7d2fe67da437069c72b17bbb5f"
        }
      ]
    }
  ]
}
