{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.5.1.aar",
          "url": "Shade-1.5.1.aar",
          "size": 106782,
          "sha512": "1080b4b5abeb6e6ec02107b623f23531c181f175fcf85e22607b91b4a1aedf3058adc4233b5993776274da147248b0740e360320a580060961e1b53fe90e2f3b",
          "sha256": "7cd657b495b0804a6199378c5f6d63f13903fe0a97dc176130d3113f46eadc3d",
          "sha1": "94081273a7432e39d8c9eb5b5c6addd2c6cf4a54",
          "md5": "3848b71482e0a81f8c4aaf8e8f2f4c74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.5.1.aar",
          "url": "Shade-1.5.1.aar",
          "size": 106782,
          "sha512": "1080b4b5abeb6e6ec02107b623f23531c181f175fcf85e22607b91b4a1aedf3058adc4233b5993776274da147248b0740e360320a580060961e1b53fe90e2f3b",
          "sha256": "7cd657b495b0804a6199378c5f6d63f13903fe0a97dc176130d3113f46eadc3d",
          "sha1": "94081273a7432e39d8c9eb5b5c6addd2c6cf4a54",
          "md5": "3848b71482e0a81f8c4aaf8e8f2f4c74"
        }
      ]
    }
  ]
}
