{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.1.aar",
          "url": "AndroidBase-1.0.1.aar",
          "size": 64805,
          "sha512": "80882d18e5902ca736c3180a4f0160e4738fb5359820a41afdd38ed990fcbdc35d3b80b1d2db08e0525e2f9edb052556c871073010fecec94cae665a39e9ee8a",
          "sha256": "77fdcdb3e9146d2d3159dd9c948d120da86e6eed3a13a6274b7c78ef5690f248",
          "sha1": "e89aeacea0e393d6de5621731e7a05dc68c3e790",
          "md5": "67d590fd8aa1be525245695bf4df78b1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.0.1.aar",
          "url": "AndroidBase-1.0.1.aar",
          "size": 64805,
          "sha512": "80882d18e5902ca736c3180a4f0160e4738fb5359820a41afdd38ed990fcbdc35d3b80b1d2db08e0525e2f9edb052556c871073010fecec94cae665a39e9ee8a",
          "sha256": "77fdcdb3e9146d2d3159dd9c948d120da86e6eed3a13a6274b7c78ef5690f248",
          "sha1": "e89aeacea0e393d6de5621731e7a05dc68c3e790",
          "md5": "67d590fd8aa1be525245695bf4df78b1"
        }
      ]
    }
  ]
}
