{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.4.0.aar",
          "url": "Shade-1.4.0.aar",
          "size": 99869,
          "sha512": "79f7cff85d34b9352a94afa4d997268e300494a402a5446e918962b2bf773a62e84fc39cdd8aba0340532754728bda82afa95386c19d32cf765d111c9568a1bd",
          "sha256": "9a589a74d2f0b443af260b536c383d9b8a39bde449e4a87a91fd369ccb9f421c",
          "sha1": "3b79728822605da10f8ea53e15e3b1279b712f51",
          "md5": "b777439ebd566155356eb90f4103fe74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.4.0.aar",
          "url": "Shade-1.4.0.aar",
          "size": 99869,
          "sha512": "79f7cff85d34b9352a94afa4d997268e300494a402a5446e918962b2bf773a62e84fc39cdd8aba0340532754728bda82afa95386c19d32cf765d111c9568a1bd",
          "sha256": "9a589a74d2f0b443af260b536c383d9b8a39bde449e4a87a91fd369ccb9f421c",
          "sha1": "3b79728822605da10f8ea53e15e3b1279b712f51",
          "md5": "b777439ebd566155356eb90f4103fe74"
        }
      ]
    }
  ]
}
