{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.0.2.aar",
          "url": "Shade-1.0.2.aar",
          "size": 63766,
          "sha512": "d135df6deabe8e7d44ef6126e6680f2aabc1ad09e4baf20c6383fc2aa48bc676376d2545f213c9dee66e1dbe19b4e3d11fbee76272246b68bb6b675fc8aeb3ff",
          "sha256": "25343f8951850b7ab38511025326834d1a43d970fb5852ac0e1c50dae086a9e6",
          "sha1": "5310c024fbb7169be34bf36c2b821ee43bc69053",
          "md5": "17cde30cf77092cea5f8b5305ab93015"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.0.2.aar",
          "url": "Shade-1.0.2.aar",
          "size": 63766,
          "sha512": "d135df6deabe8e7d44ef6126e6680f2aabc1ad09e4baf20c6383fc2aa48bc676376d2545f213c9dee66e1dbe19b4e3d11fbee76272246b68bb6b675fc8aeb3ff",
          "sha256": "25343f8951850b7ab38511025326834d1a43d970fb5852ac0e1c50dae086a9e6",
          "sha1": "5310c024fbb7169be34bf36c2b821ee43bc69053",
          "md5": "17cde30cf77092cea5f8b5305ab93015"
        }
      ]
    }
  ]
}
