{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.5.0.aar",
          "url": "Shade-1.5.0.aar",
          "size": 85638,
          "sha512": "d4c8b0560b3bf79b0233e69fa6f7ac482abd2a62a9b6d15b387461ec4bf41f39c884271af4f20470c12da4d2670e13a11a0a5d4ec5436043d9fc31d95808635a",
          "sha256": "4dc05976f253d968aa77988159811b4e9c25d559413010a5d135ab11e2d6853c",
          "sha1": "fa5b3ef47699160d54e9dce753dae379a1bae1f9",
          "md5": "3917f45704a774f9fec72674ac608c04"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.5.0.aar",
          "url": "Shade-1.5.0.aar",
          "size": 85638,
          "sha512": "d4c8b0560b3bf79b0233e69fa6f7ac482abd2a62a9b6d15b387461ec4bf41f39c884271af4f20470c12da4d2670e13a11a0a5d4ec5436043d9fc31d95808635a",
          "sha256": "4dc05976f253d968aa77988159811b4e9c25d559413010a5d135ab11e2d6853c",
          "sha1": "fa5b3ef47699160d54e9dce753dae379a1bae1f9",
          "md5": "3917f45704a774f9fec72674ac608c04"
        }
      ]
    }
  ]
}
