{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidWidget",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.6.5.aar",
          "url": "AndroidWidget-1.6.5.aar",
          "size": 226477,
          "sha512": "1f9f3c199a49d0c9231cf2e46c7edc45dc61dd0209631ec0c6a12d73797dd0418dfaea1cecc8bd9fba2e9c8ee0b66c00679ea53c912de07cd7da4f9bd8552bdf",
          "sha256": "d109ecec95faae744e22d56083fb09c1bc15f3ddcdf7537660474bf90f28526a",
          "sha1": "0713fb47c23e050d1912dfde12f707b20cf6bd02",
          "md5": "1417cb9fbba07f5a3955ccb4a73a2254"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "LocalBroadcastUtil",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv",
          "version": {
            "requires": "1.2.14"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidWidget-1.6.5.aar",
          "url": "AndroidWidget-1.6.5.aar",
          "size": 226477,
          "sha512": "1f9f3c199a49d0c9231cf2e46c7edc45dc61dd0209631ec0c6a12d73797dd0418dfaea1cecc8bd9fba2e9c8ee0b66c00679ea53c912de07cd7da4f9bd8552bdf",
          "sha256": "d109ecec95faae744e22d56083fb09c1bc15f3ddcdf7537660474bf90f28526a",
          "sha1": "0713fb47c23e050d1912dfde12f707b20cf6bd02",
          "md5": "1417cb9fbba07f5a3955ccb4a73a2254"
        }
      ]
    }
  ]
}
