{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.6.aar",
          "url": "Shade-1.3.6.aar",
          "size": 92915,
          "sha512": "658fcd8f4016188f4528da7c1c7973da2f445104eaaf966b7f541dbf09012510dc46d20b471ff1b9e435d0045a3ad044e5f00ab8d42600361aa175d22789f1c1",
          "sha256": "6bf4cab1829ec89645eaf814d71f17c8620e5949b9d1dff41109f80221689796",
          "sha1": "fe85295f5221b16535496a908a94ac948c631d36",
          "md5": "521ec84502be40ec41fcc5b0db6b287f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.6.aar",
          "url": "Shade-1.3.6.aar",
          "size": 92915,
          "sha512": "658fcd8f4016188f4528da7c1c7973da2f445104eaaf966b7f541dbf09012510dc46d20b471ff1b9e435d0045a3ad044e5f00ab8d42600361aa175d22789f1c1",
          "sha256": "6bf4cab1829ec89645eaf814d71f17c8620e5949b9d1dff41109f80221689796",
          "sha1": "fe85295f5221b16535496a908a94ac948c631d36",
          "md5": "521ec84502be40ec41fcc5b0db6b287f"
        }
      ]
    }
  ]
}
