{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "AndroidBase",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.3.1.aar",
          "url": "AndroidBase-1.3.1.aar",
          "size": 104905,
          "sha512": "f2040c99f18c2c582a1b7b8e7e7d0da2ad2e2a8358763ff49b0ef595892856fd3ab51228b9002006179b9544b7eba1d6019dc9931d6d1f528d2f845a0c52aebf",
          "sha256": "062ce16928c4b022d9d7442e0f623c4fc0371f4cc6081c7d22f78418ec305c8a",
          "sha1": "5ca2ffd8c26ba1e90e31903c905c3db2d2e8abf3",
          "md5": "5005a57e1bae866b8bad9236ed710fd8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "Shade",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.3.1.aar",
          "url": "AndroidBase-1.3.1.aar",
          "size": 104905,
          "sha512": "f2040c99f18c2c582a1b7b8e7e7d0da2ad2e2a8358763ff49b0ef595892856fd3ab51228b9002006179b9544b7eba1d6019dc9931d6d1f528d2f845a0c52aebf",
          "sha256": "062ce16928c4b022d9d7442e0f623c4fc0371f4cc6081c7d22f78418ec305c8a",
          "sha1": "5ca2ffd8c26ba1e90e31903c905c3db2d2e8abf3",
          "md5": "5005a57e1bae866b8bad9236ed710fd8"
        }
      ]
    }
  ]
}
