{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.2.aar",
          "url": "Shade-1.2.2.aar",
          "size": 65081,
          "sha512": "e4f15652e0e9ac96bcae853f10a665e8a2462b3ae03bb1f0618ddf500ef26fed33b1b9ee6c269147314109a399d73db7b7b83c9c4ffa5158158f1dca79937584",
          "sha256": "0a9fc8cf731ca1b34fa2199a7e7266e4c23f66f577ee9164d3830b0f85419d55",
          "sha1": "b22c64b23691f0d56fb9c3691ddb792977f5d7b5",
          "md5": "dd24f83c1e31546862712c56e2c27cf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.2.aar",
          "url": "Shade-1.2.2.aar",
          "size": 65081,
          "sha512": "e4f15652e0e9ac96bcae853f10a665e8a2462b3ae03bb1f0618ddf500ef26fed33b1b9ee6c269147314109a399d73db7b7b83c9c4ffa5158158f1dca79937584",
          "sha256": "0a9fc8cf731ca1b34fa2199a7e7266e4c23f66f577ee9164d3830b0f85419d55",
          "sha1": "b22c64b23691f0d56fb9c3691ddb792977f5d7b5",
          "md5": "dd24f83c1e31546862712c56e2c27cf4"
        }
      ]
    }
  ]
}
