{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.0.aar",
          "url": "Shade-1.2.0.aar",
          "size": 58741,
          "sha512": "89740679674c95d62d18c678de87b2ba445762fcebc72ec2e8fbe45db25261fedc56945e7c488d1dbb827f22115b5a4979e1ff9d84f513dc7f46c2e1720f8287",
          "sha256": "4d29cdd59924dfef25f60f929b3c9827dd42f58ca384a939237bd821be1aa3da",
          "sha1": "ba90cbf90021cc854baada98a175d1dcb12040e0",
          "md5": "32b35deba5579694e6cbc86dd731f464"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.0.aar",
          "url": "Shade-1.2.0.aar",
          "size": 58741,
          "sha512": "89740679674c95d62d18c678de87b2ba445762fcebc72ec2e8fbe45db25261fedc56945e7c488d1dbb827f22115b5a4979e1ff9d84f513dc7f46c2e1720f8287",
          "sha256": "4d29cdd59924dfef25f60f929b3c9827dd42f58ca384a939237bd821be1aa3da",
          "sha1": "ba90cbf90021cc854baada98a175d1dcb12040e0",
          "md5": "32b35deba5579694e6cbc86dd731f464"
        }
      ]
    }
  ]
}
