{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.7.aar",
          "url": "Shade-1.3.7.aar",
          "size": 99331,
          "sha512": "d953d15703446124fd5b473ff9ae8a5498e9b8c5fde862d863c870fac8ed626c28397aa08037b3d4f2d4821b1cb1656eb2e54ea229808612b9a17e3e3bc83d22",
          "sha256": "acca87258ed696d3704bcd6f7dac5c55d4845cbcbf99f7c087c97140b1b110c9",
          "sha1": "993b102c91da3b9a17a0502a59d19e2f1d2bf968",
          "md5": "f3546db43fce08474d0681fcf6b7d366"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.7.aar",
          "url": "Shade-1.3.7.aar",
          "size": 99331,
          "sha512": "d953d15703446124fd5b473ff9ae8a5498e9b8c5fde862d863c870fac8ed626c28397aa08037b3d4f2d4821b1cb1656eb2e54ea229808612b9a17e3e3bc83d22",
          "sha256": "acca87258ed696d3704bcd6f7dac5c55d4845cbcbf99f7c087c97140b1b110c9",
          "sha1": "993b102c91da3b9a17a0502a59d19e2f1d2bf968",
          "md5": "f3546db43fce08474d0681fcf6b7d366"
        }
      ]
    }
  ]
}
