{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bonepeople.android.lib",
    "module": "Shade",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.1.aar",
          "url": "Shade-1.3.1.aar",
          "size": 72592,
          "sha512": "1824b0960db1682e91fa78ccea9333c93a46a565a7cab0b99178cf0426f86710c6c783b80046548bdc78d30911369649604f80230b32e91e6b9e8b4b8e2c247f",
          "sha256": "f9ee732e784fe77ffcffc0bd6dbb0dae081e4c7857b8516650699215a6620606",
          "sha1": "f329471986977468cd95478424792c6efb150c21",
          "md5": "8a4b77cdfa024ef7d4e4a08b2b6dfe66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "2.2.4"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.3.1.aar",
          "url": "Shade-1.3.1.aar",
          "size": 72592,
          "sha512": "1824b0960db1682e91fa78ccea9333c93a46a565a7cab0b99178cf0426f86710c6c783b80046548bdc78d30911369649604f80230b32e91e6b9e8b4b8e2c247f",
          "sha256": "f9ee732e784fe77ffcffc0bd6dbb0dae081e4c7857b8516650699215a6620606",
          "sha1": "f329471986977468cd95478424792c6efb150c21",
          "md5": "8a4b77cdfa024ef7d4e4a08b2b6dfe66"
        }
      ]
    }
  ]
}
