{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "Shade",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.3.aar",
          "url": "Shade-1.2.3.aar",
          "size": 65378,
          "sha512": "ab9bc1919bf1830cae55c0a6d208a10a4fcf7573b12df28e567db5f75c61e19fbaddfeee1936558d0a0789d4e0d7984c782edcbc3770ba274f4051225369dc16",
          "sha256": "9ced7573ccd11891c3bf807daf53a7b6f3420f1a231e8a5ea3c89f751715117b",
          "sha1": "50901530a0b642b277ffb4504e724e368c4f500f",
          "md5": "bb6569cb5570ce601616613491dc6cbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shade-1.2.3.aar",
          "url": "Shade-1.2.3.aar",
          "size": 65378,
          "sha512": "ab9bc1919bf1830cae55c0a6d208a10a4fcf7573b12df28e567db5f75c61e19fbaddfeee1936558d0a0789d4e0d7984c782edcbc3770ba274f4051225369dc16",
          "sha256": "9ced7573ccd11891c3bf807daf53a7b6f3420f1a231e8a5ea3c89f751715117b",
          "sha1": "50901530a0b642b277ffb4504e724e368c4f500f",
          "md5": "bb6569cb5570ce601616613491dc6cbd"
        }
      ]
    }
  ]
}
