{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bonepeople",
    "module": "AndroidBase",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.2.0.aar",
          "url": "AndroidBase-1.2.0.aar",
          "size": 96219,
          "sha512": "5e0d349b92b78cc242ec4156a43d179fe26f5f9b6be0bb25ff433924b1179bac408415fca17b14505a97b7c418daf079d15b807a2788cd19d4ba9fdade8405aa",
          "sha256": "c335ede682d568eb3bf018ac0917b04a4bd57a41392417760244a3d1240984b6",
          "sha1": "f1e15e62719486a520638d9f5dab5e3cfd1da1bb",
          "md5": "ae72d45c089a149414f6c710f3b00535"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bonepeople",
          "module": "AndroidWidget",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.gyf.immersionbar",
          "module": "immersionbar-ktx",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "AndroidBase-1.2.0.aar",
          "url": "AndroidBase-1.2.0.aar",
          "size": 96219,
          "sha512": "5e0d349b92b78cc242ec4156a43d179fe26f5f9b6be0bb25ff433924b1179bac408415fca17b14505a97b7c418daf079d15b807a2788cd19d4ba9fdade8405aa",
          "sha256": "c335ede682d568eb3bf018ac0917b04a4bd57a41392417760244a3d1240984b6",
          "sha1": "f1e15e62719486a520638d9f5dab5e3cfd1da1bb",
          "md5": "ae72d45c089a149414f6c710f3b00535"
        }
      ]
    }
  ]
}
